/**
 * schema для создания объекта
 * для перспективного использования
 */
const SCHEMA_TYPES = {
    INTERNAL_TYPES:{
        KEYS:{
            DATA:'DATA',
            KNOT:'KNOT',
        },
    },
    CONTENT_TYPES:{
        SCALAR:{
            KEYS:{
                STRING:'string',  
                BOOLEAN:'boolean',
                NUMBER:'number',
            },
        },
        OBJECT:{
            KEYS:{
                OBJECT:'object',
            },
            INSTANCIES:{
                BUFFER:'Buffer',
            }
        }
    }
}
const { INTERNAL_TYPES, CONTENT_TYPES } = SCHEMA_TYPES;

const FILE_DATA_SCHEMA = {
    STRUCT:{
        GROUP_ID:{
            KEY:'groupId',
            TYPE:INTERNAL_TYPES.KEYS.DATA,
            CONTENT_TYPE:CONTENT_TYPES.SCALAR.KEYS.STRING,
            CONSTRUCTOR:null,
            NESTED_SCHEMA:null,
        },
        TABLE_NAME:{
            KEY:'tableName',
            TYPE:INTERNAL_TYPES.KEYS.DATA,
            CONTENT_TYPE:CONTENT_TYPES.SCALAR.KEYS.STRING,
            CONSTRUCTOR:null,
            NESTED_SCHEMA:null,
        },
        DATA:{
            KEY:'data',
            TYPE:INTERNAL_TYPES.KEYS.KNOT,
            CONTENT_TYPE:CONTENT_TYPES.OBJECT.KEYS.OBJECT,
            CONSTRUCTOR:Object,
            NESTED_SCHEMA:{
                FILE_BODY:{
                    KEY:'fileBody',
                    TYPE:INTERNAL_TYPES.KEYS.DATA,
                    CONTENT_TYPE:CONTENT_TYPES.OBJECT.KEYS.OBJECT,
                    CONSTRUCTOR:Buffer,
                    NESTED_SCHEMA:null,
                },
                FILE_MIME:{
                    KEY:'fileMIME',
                    TYPE:INTERNAL_TYPES.KEYS.DATA,
                    CONTENT_TYPE:CONTENT_TYPES.SCALAR.KEYS.STRING,
                    CONSTRUCTOR:null,
                    NESTED_SCHEMA:null,
                },
                FILE_NAME:{
                    KEY:'fileName',
                    TYPE:INTERNAL_TYPES.KEYS.DATA,
                    CONTENT_TYPE:CONTENT_TYPES.SCALAR.KEYS.STRING,
                    CONSTRUCTOR:null,
                    NESTED_SCHEMA:null,
                },
                COLUMN_NAME:{
                    KEY:'columnName',
                    TYPE:INTERNAL_TYPES.KEYS.DATA,
                    CONTENT_TYPE:CONTENT_TYPES.SCALAR.KEYS.STRING,
                    CONSTRUCTOR:null,
                    NESTED_SCHEMA:null,
                },
            },
        },
    },
}


const MULTITABLE_AGENT_OUT_DATA_SCHEMAS = {
    FILE:{
        MIME:{
            KEY:'mime',
            TYPE:'DATA',
            CONTENT_TYPE:'string',
            NESTED_SCHEMA:null,
        },
        FILE_NAME:{
            KEY:'fileName',
            TYPE:'DATA',
            CONTENT_TYPE:'string',
            NESTED_SCHEMA:null,
        },
        FILE_BODY:{
            KEY:'fileBody',
            TYPE:'DATA',
            CONTENT_TYPE:'object',
            NESTED_SCHEMA:null,
        },
        COLUMN_NAME:{
            KEY:'columnName',
            TYPE:'DATA',
            CONTENT_TYPE:'string',
            NESTED_SCHEMA:null,
        },
    },
    COLUMN:{
        COLUMN_NAME:{
            KEY:'columnName',
            TYPE:'KNOT',
            CONTENT_TYPE:'object',
            NESTED_SCHEMA:{
                DATA_TYPE:{
                    KEY:'dataType',
                    TYPE:'DATA',
                    CONTENT_TYPE:'string',
                    NESTED_SCHEMA:null,
                },
                DATA:{
                    KEY:'data',
                    TYPE:'DATA',
                    CONTENT_TYPE:'object',
                    NESTED_SCHEMA:null,
                },
            }
        },
        
    },
}

module.exports = { FILE_DATA_SCHEMA, MULTITABLE_AGENT_OUT_DATA_SCHEMAS }